defaultPortal: igomoon-reference
portals:
  - name: igomoon-reference
    portalId: 8632619
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CNj667bWLhIIAA0ADAAA4AEYq_KOBCCL-ekFKO7pDDIZAJBIFnWu6gH5tH-ammzvsKmkrQCCDD-VMTogAAAEQQAAAHgAAAAAAAAAAIABAAAAAAAEwADAB2D-_zFCGQCQSBZ1TBbKD4z6QdKBkFn-dEGtn4_uOrs
        expiresAt: '2020-10-26T21:40:29.150Z'
    personalAccessKey: >-
      CiQ4NDBhZDkxYy00NjQyLTQzNjUtOTFiYS01OGIxZmZmY2YyNDcQq_KOBBiL-ekFKhkABeaRgnvRaknPOEGwxp2eYqZ0A5kyZhB-
