defaultPortal: igomoon-reference
portals:
  - name: igomoon-reference
    portalId: 8632619
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CPTil63WLhIIAA0ADAAA4AEYq_KOBCCL-ekFKO7pDDIZAMiQM-P00xJRmhyVLUWqkdNEHgwluJVOGDogAAAEQQAAAHgAAAAAAAAAAIABAAAAAAAEwADAB2D-_zFCGQDIkDPjrv432xU8ARgg9achBzAuDufdC6c
        expiresAt: '2020-10-26T16:02:55.482Z'
    personalAccessKey: >-
      CiQ4NDBhZDkxYy00NjQyLTQzNjUtOTFiYS01OGIxZmZmY2YyNDcQq_KOBBiL-ekFKhkABeaRgnvRaknPOEGwxp2eYqZ0A5kyZhB-
